sudo: required

language: erlang

otp_release:
  - 20.1

cache:
  directories:
  - $HOME/.cache/rebar3

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script: ./rebar3 as test do eunit,ct && ./rebar3 dialyzer && ./rebar3 coveralls send
